apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: demo
spec:
  type: LoadBalancer  # gives you an external URL (ELB)
  selector:
    app: hello
  ports:
    - port: 80
      targetPort: 8080
