apiVersion: v1
kind: Service
metadata:
  name: mysql-hl
  namespace: demo
spec:
  clusterIP: None
  selector: { app: mysql }
  ports: [{ name: mysql, port: 3306, targetPort: 3306 }]
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: demo
spec:
  selector: { app: mysql }
  ports: [{ name: mysql, port: 3306, targetPort: 3306 }]
