apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: demo
spec:
  replicas: 2
  selector: { matchLabels: { app: web } }
  template:
    metadata:
      labels: { app: web }
    spec:
      containers:
      - name: web
        image: REPLACE_ME_ECR_WEB:REPLACE_ME_TAG
        ports: [{ containerPort: 80 }]
        readinessProbe:
          httpGet: { path: /healthz, port: 80 }
          initialDelaySeconds: 5
        livenessProbe:
          httpGet: { path: /healthz, port: 80 }
          initialDelaySeconds: 15
        resources:
          requests: { cpu: "50m", memory: "64Mi" }
          limits:   { cpu: "200m", memory: "256Mi" }
